---
- name: devops pipeline
  hosts: client1
  gather_facts: yes
  become: yes
  tasks:
    - name: pull from docker hub
      shell: docker pull sheetalagarwal/devops_pipeline_scical_img

    - name: get container info
      docker_container_info:
        name: devops_container
      register: result

    - name: remove container if exists
      shell: docker rm devops_container
      when: result.exists
      
    - name: create container
      shell : docker run -it -d --name devops_container sheetalagarwal/devops_pipeline_scical_img 
